### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by Barcors** [nassir-malik/IOT-Smart-Temperature-Switch-With-Alexa-NodeMcu#1]
Good day Mr. Nassir,
I wanted to try the way like you have done with Sonoff switch and Alexa but I am not success. And seems to be this is because of Heroku. First fail was because of Python. Heroku was telling me that app is using old unsuported Python. Then I cloned your repository on github to fix that and tried launch app on Heroku once again. Generaly it looks OK but my sonof refuses to connect:
Current humidity = 50.00%  temperature = 22.00C  71.60F  
Disconnected! 
Connecting...
Current humidity = 50.00%  temperature = 22.00C  71.60F  
Disconnected! 
Connecting...
Disconnected! 
Connecting...
Current humidity = 49.00%  temperature = 23.00C  73.40F  
Current humidity = 48.00%  temperature = 23.00C  73.40F  
Disconnected! 
Connecting...
Current humidity = 49.00%  temperature = 22.00C  71.60F  
Disconnected! 
Connecting...
And that is forever.
My setting in sketch: 
char host[] = "smartempswitch.herokuapp.com// "; //- better your Heroku domain name like  "smarttempswitch.herokuapp.com"
Might be you have some thoughts about that. 
Thank you.
Barcors

**Comment by nassir-malik** [comment]
Remove the slashes from heroku app name.

-Thanks
====================================================
Nassir

**Comment by Barcors** [comment]
Do you mean like this:
char host[] = "smartempswitch.herokuapp.com"; //- better your Heroku domain name like "smarttempswitch.herokuapp.com"

**Comment by Barcors** [comment]
Thank you Mr. Nassir - it worked.  You see - I have nothing to do with any coding and I am sorry if my questions are dumb for you. I just trying to replicate interesting projects for myself.
Relay now reconnecting to Heroku each minute - is this normal?
Is this Heroku is essential? Can it be done without that service at all? Just relay and Alexa?
Thank you.

**Comment by Barcors** [comment]
Issue's
